deployment:
  name: nginx
  image: nginx
  tag: latest
  containerPort: 80
  replicas: 0

deployment2:
  name: nginx2
  image: gcr.io/google-samples/hello-app
  tag: "2.0"
  containerPort: 8080
  replicas: 0

service:
  name: nginx-service
  port: 80
  type: NodePort

service2:
  name: nginx-service2
  port: 80
  targetPort: 8080
  type: NodePort
  selector: nginx2

ingress:
  name: nginx-ingress
