apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}
spec:
  type: {{ .Values.service2.type }}
  selector:
    app: {{ .Values.service2.selector }}
  ports:
    - protocol: TCP
      port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.targetPort }}
